language: php
sudo: true
php:
  - 7.2
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev --ignore-platform-reqs
  - chmod +x ./scripts/travis.sh
script:
  - ./scripts/travis.sh
